name: check-secret-after-test

on: [push]

jobs:
  check-secret-after-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: env-test
      - name: check current secret XXX_TEST
        run: |
          XXX_TEST_UPLOADED=$(cat .env.test | cut -d= -f2)
          echo "upload: $XXX_TEST_UPLOADED, in secret: x.${XXX_TEST:1}"

          if [ "$XXX_TEST_UPLOADED" != "$XXX_TEST" ]; then
            exit 1
          fi
        env:
          XXX_TEST: ${{ secrets.XXX_TEST }}
