name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn type
      - run: yarn lint
      - run: yarn test --ci
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
      - run: yarn dev list
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}

  print-secret:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: check current secret XXX_TEST
        run: echo $XXX_TEST | tr a-z A-Z
        env:
          XXX_TEST: ${{ secrets.XXX_TEST }}

      - name: check current secret YYY_TEST
        run: echo $YYY_TEST | tr a-z A-Z
        env:
          YYY_TEST: ${{ secrets.YYY_TEST }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1.4.0
        if: success() && github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.NPM_TOKEN }}
